server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  h2:
    console.enabled: true